apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web
        image: arunpusawant/okteto:latest
        command: ["./run.sh"]
        resources:
          limits:
            memory: "4Gi"
            cpu: "2" 
