apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web
        image: registry.cloud.okteto.net/arunpusawant/web:okteto
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"        

---

apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: web
